
; ===================================================================================
; Install PlatformIO and CH32V:
; https://pio-ch32v.readthedocs.io/en/latest/
; https://github.com/Community-PIO-CH32V/platform-ch32v
; ===================================================================================

[platformio]
; Uncomment to build a specific game instead of the bootloader:
; src_dir = src_games/OSDemo
; src_dir = src_games/3in1A
default_envs = lab_machines

[env:CH32X035]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
framework = arduino
board = phsi245_gameboy
board_build.variants_dir = variant
build_flags = -I. -D F_CPU=48000000 -D NO_GLOBAL_EEPROM -D HW_VERSION=2
board_build.use_lto = yes
upload_protocol = minichlink
upload_command = chprog $SOURCE

[env:lab_machines]
extends = env:CH32X035
; Technically upload_protocol should be custom since we have a custom commmand,
; but then $SOURCE is defined badly....
; Need to run pip install chprog in pio terminal first.
upload_protocol = minichlink
upload_command = .venv/bin/python prog_tools/program.py $SOURCE

[env:v2]
extends = env:lab_machines
build_flags = ${env:CH32X035.build_flags} -D HW_VERSION=2

[env:v1]
extends = env:lab_machines
build_flags = ${env:CH32X035.build_flags} -D HW_VERSION=1
